---
version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
      - run:
          name: Install Terraform
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            brew install terraform node@12
      - run:
          name: Install project dependencies
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make deps
      - run:
          name: Prepare test
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make test-prep
      - run:
          name: Run tests
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make test-all
