---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
      - run:
          name: Install Terraform
          command: |
            export PATH="$HOME/.linuxbrew/bin:$PATH"
            brew install terraform
      - run:
          name: Install project dependencies
          command: |
            export PATH="$HOME/.linuxbrew/bin:$PATH"
            make deps
      - run:
          name: Prepare test
          command: |
            export PATH="$HOME/.linuxbrew/bin:$PATH"
            make test-prep
      - run:
          name: Run tests
          command: |
            export PATH="$HOME/.linuxbrew/bin:$PATH"
            make test-all
