---
version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
      - run:
          name: Install Terraform
          environment:
            PATH: "/home/linuxbrew/.linuxbrew/bin:PATH"
          command: |
            brew install terraform node@12
            brew link --force --overwrite node@12
      - run:
          name: Install project dependencies
          environment:
            PATH: "/home/linuxbrew/.linuxbrew/opt/node@12/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"
          command: |
            make deps
      - run:
          name: Prepare test
          environment:
            PATH: "/home/linuxbrew/.linuxbrew/opt/node@12/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"
          command: |
            make test-prep
      - run:
          name: Run tests
          environment:
            PATH: "/home/linuxbrew/.linuxbrew/opt/node@12/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"
          command: |
            make test-all
